# Generated by Django 3.0.3 on 2020-02-19 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('background_image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_image', models.FileField(blank=True, unique=True, upload_to='./images')),
            ],
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('color_palettes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_color', models.CharField(max_length=25)),
                ('button_color', models.CharField(max_length=25)),
                ('navbar_color', models.CharField(max_length=25)),
                ('icon_color', models.CharField(max_length=25)),
                ('container_color', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'ColorPalettes',
            },
        ),
        migrations.CreateModel(
            name='FontTable',
            fields=[
                ('font_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('font_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('settingid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BackgroundImage')),
                ('color_palettes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ColorPalette')),
                ('font_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.FontTable')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
