# Generated by Django 3.0.3 on 2020-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_backgroundimage_colorpalette_fonttable_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='background_image',
            field=models.ImageField(blank=True, unique=True, upload_to='./images'),
        ),
    ]
